services:
  web:
    build: .
    container_name: django_web_postgres
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - db

    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATA_UPLOAD_MAX_MEMORY_SIZE=5242880

    # environment:
    #   - DJANGO_SETTINGS_MODULE=task_manager.settings
    #   - POSTGRES_DB=taskdb
    #   - POSTGRES_USER=taskuser
    #   - POSTGRES_PASSWORD=taskpassword
    #   - POSTGRES_HOST=db
    #   - POSTGRES_PORT=5432
    #   - DATA_UPLOAD_MAX_MEMORY_SIZE=5242880

  db:
    image: postgres:latest
    container_name: django_db_postgres
    restart: always
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  postgres_data:
