services:
  web:
    build: .
    container_name: django_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=task_manager.settings
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - DATA_UPLOAD_MAX_MEMORY_SIZE=5242880

  mongo:
    image: mongo:latest
    # container_name: mongo_db2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  static_volume:
