services:
  web:
    build: .
    container_name: django_web_postgres
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - TZ=Asia/Bangkok  # Đặt múi giờ cho container
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATA_UPLOAD_MAX_MEMORY_SIZE=5242880
    networks:
      - petenet


  nginx:
    image: nginx:latest
    container_name: nginx_https
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - petenet
  db:
    image: postgres:latest
    container_name: django_db_postgres
    restart: always
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petenet

networks:
  petenet:

volumes:
  static_volume:
  postgres_data:
